---
title: "Class 14: Genome Informatics I"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Asthma SNPs in MXL population


Read file from Ensemble:
http://uswest.ensembl.org/Homo_sapiens/Variation/Sample?db=core;r=17:39894595-39895595;v=rs8067378;vdb=variation;vf=362656008#373531_tablePanel

```{r}
mxl <- read.csv("373531-SampleGenotypes-Homo_sapiens_Variation_Sample_rs8067378.csv")
head(mxl)
```

```{r}
table(mxl$Genotype..forward.strand.)
```

```{r}
sum(mxl$Genotype..forward.strand. == "G|G")

table(mxl$Genotype..forward.strand.)/ nrow(mxl) *100
```


## RNA-Seq

Q8: Does the first sequence have good quality?
```{r}
q <- "DDDDCDEDCDDDDBBDDDCC@"
library(seqinr)
library(gtools)

asc(s2c(q)) - 33
```


## Population Scale analysis

Does the genotype for rs8067378 influence expression of the important asthma linked genes we found?
```{r}
geno <- read.table("rs8067378_ENSG00000172057.6.txt")
head(geno)
```

```{r}
table(geno$geno)
```

```{r}
inds.gg <- geno$geno == "G/G"
summary(geno$exp[inds.gg])
```

```{r}
inds.aa <- geno$geno == "A/A"
summary(geno$exp[inds.aa])
```

```{r}
inds.ag <- geno$geno == "A/G"
summary(geno$exp[inds.ag])
```

Some nice figure that shows the distribution of these expression values?

```{r}
boxplot(exp ~ geno, geno)
```

