---
title: "Class 13: Structure-based Drug Discovery"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Prepare HIV-protease molecule for docking

First, get a pDB structure from the online database then clean it up for docking.

```{r}
library(bio3d)
file.name <- get.pdb("1hsg")
hiv <- read.pdb(file.name)
hiv
```

Q1: What is the name of the two non protein resid values in this structure? What does resid correspond to and how would you get a listing of all reside values in this structure? 
HOH and MK1

```{r}
prot <- trim.pdb(hiv, "protein")
lig <- trim.pdb(hiv, "ligand")
write.pdb(prot, file="1hsg_protein.pdb")
write.pdb(lig, file="1hsg_ligand.pdb")
```

Read in autodoc results.
```{r}
library(bio3d)

res <- read.pdb("all.pdbqt", multi=TRUE)
write.pdb(res, file="results.pdb")
```

```{r}
res <- read.pdb("all.pdbqt", multi=TRUE)
ori <- read.pdb("ligand.pdbqt")
rmsd(ori, res)
```

## Normal Code Analysis

```{r}
pdb <- read.pdb("1HEL")

m <- nma(pdb)
plot(m)
```

```{r}
mktrj(m, mode=7, file="nma_7.p")
```

